=== Greegko/battleground/packages/core/src/unit.schema.json
{
  "$id": "https://greegko.com/unit.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": { "type": "string" },
      "spriteId": { "type": "string" },
      "moveSpeed": { "type": "number" },
      "maxHp": { "type": "number" },
      "action": { "$ref": "#/$defs/action" },
      "size": { "type": "number" },
      "effects": { "type": "array", "items": { "$ref": "#/$defs/effect" } }
    },
    "additionalProperties": false,
    "requiredProperties": ["id", "spriteId", "moveSpeed", "maxHp", "action", "size", "effects"]
  },

  "$defs": {
    "seekCondition": {
      "oneOf": [
        { "enum": ["enemy-team", "alive", "dead", "same-team", "damaged"] },
        {
          "type": "array",
          "prefixItems": [
            { "const": "in-distance" },
            {
              "type": "object",
              "properties": { "distance": { "type": "number" } },
              "requiredProperties": ["distance"],
              "additionalProperties": false
            }
          ],
          "items": false
        }
      ]
    },

    "effect": {
      "type": "object",
      "properties": { "type": { "enum": ["revive", "heal", "dmg", "spawn-unit", "armor"] } }
    },

    "dmgType": { "enum": ["pure", "physical", "magic"] },

    "action": {
      "type": "object",
      "properties": {
        "animation": { "type": "string" },
        "seekTargetCondition": { "type": "array", "items": { "$ref": "#/$defs/seekCondition" } },
        "distance": { "type": "number" },
        "cooldown": { "type": "number" },
        "projectileId": { "type": "string" },
        "projectileSpeed": { "type": "number" },
        "speed": { "type": "number" },
        "effect": { "type": "array", "items": { "$ref": "#/$defs/effect" } },
        "hitEffect": { "type": "array", "items": { "$ref": "#/$defs/effect" } }
      },
      "dependentRequired": {
        "projectileId": ["projectileSpeed"]
      },
      "additionalProperties": false
    }
  }
}

=== Greegko/battleground/src/scenarios/units.json
[
  {
    "id": "skeleton",
    "spriteId": "skeleton",
    "moveSpeed": 2,
    "maxHp": 100,
    "action": {
      "animation": "attack",
      "seekTargetCondition": ["alive", "enemy-team"],
      "distance": 40,
      "cooldown": 120,
      "speed": 30,
      "hitEffect": [{ "type": "dmg", "args": 20 }]
    },
    "size": 32
  },
  {
    "id": "archer",
    "spriteId": "archer",
    "moveSpeed": 2,
    "maxHp": 100,
    "action": {
      "animation": "attack",
      "seekTargetCondition": ["alive", "enemy-team"],
      "projectileId": "projectile",
      "distance": 400,
      "cooldown": 120,
      "speed": 30,
      "projectileSpeed": 5,
      "hitEffect": [{ "type": "dmg", "args": 20 }]
    },
    "size": 32
  },
  {
    "id": "necromancer",
    "spriteId": "inquisitor",
    "moveSpeed": 2,
    "maxHp": 100,
    "action": {
      "animation": "attack",
      "seekTargetCondition": ["dead", "same-team"],
      "distance": 100,
      "cooldown": 500,
      "speed": 60,
      "hitEffect": [{ "type": "revive" }]
    },
    "size": 32
  },
  {
    "id": "priest",
    "spriteId": "inquisitor",
    "moveSpeed": 2,
    "maxHp": 100,
    "action": {
      "animation": "attack",
      "seekTargetCondition": ["alive", "same-team", "damaged"],
      "distance": 100,
      "cooldown": 150,
      "speed": 60,
      "hitEffect": [{ "type": "heal", "args": 20 }]
    },
    "size": 32
  }
]
