=== Greegko/battleground/packages/core/schemas/unit-config.schema.json
{
  "$ref": "#/definitions/UnitConfig",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "Action": {
      "additionalProperties": false,
      "properties": {
        "animation": {
          "$ref": "#/definitions/Animation"
        },
        "cooldown": {
          "type": "number"
        },
        "distance": {
          "type": "number"
        },
        "effect": {
          "items": {
            "$ref": "#/definitions/Effect"
          },
          "type": "array"
        },
        "hitEffect": {
          "items": {
            "$ref": "#/definitions/Effect"
          },
          "type": "array"
        },
        "projectileId": {
          "type": "string"
        },
        "projectileSpeed": {
          "type": "number"
        },
        "seekTargetCondition": {
          "items": {
            "$ref": "#/definitions/SeekCondition"
          },
          "type": "array"
        },
        "speed": {
          "type": "number"
        }
      },
      "required": [
        "cooldown",
        "speed"
      ],
      "type": "object"
    },
    "Animation": {
      "const": "attack",
      "type": "string"
    },
    "ArmorEffect": {
      "additionalProperties": false,
      "properties": {
        "dmgType": {
          "$ref": "#/definitions/DmgType"
        },
        "power": {
          "type": "number"
        },
        "type": {
          "const": "armor",
          "type": "string"
        }
      },
      "required": [
        "type",
        "dmgType",
        "power"
      ],
      "type": "object"
    },
    "DmgEffect": {
      "additionalProperties": false,
      "properties": {
        "dmgType": {
          "$ref": "#/definitions/DmgType"
        },
        "power": {
          "type": "number"
        },
        "type": {
          "const": "dmg",
          "type": "string"
        }
      },
      "required": [
        "type",
        "dmgType",
        "power"
      ],
      "type": "object"
    },
    "DmgType": {
      "enum": [
        "pure",
        "physical",
        "magic",
        "fire"
      ],
      "type": "string"
    },
    "DotEffect": {
      "additionalProperties": false,
      "properties": {
        "dmgType": {
          "$ref": "#/definitions/DmgType"
        },
        "interval": {
          "type": "number"
        },
        "period": {
          "type": "number"
        },
        "power": {
          "type": "number"
        },
        "state": {
          "additionalProperties": false,
          "properties": {
            "intervalState": {
              "type": "number"
            },
            "remainingPeriod": {
              "type": "number"
            }
          },
          "required": [
            "intervalState",
            "remainingPeriod"
          ],
          "type": "object"
        },
        "type": {
          "const": "dot",
          "type": "string"
        }
      },
      "required": [
        "type",
        "dmgType",
        "power",
        "interval",
        "period"
      ],
      "type": "object"
    },
    "Effect": {
      "anyOf": [
        {
          "$ref": "#/definitions/GenericEffect"
        },
        {
          "$ref": "#/definitions/HealEffect"
        },
        {
          "$ref": "#/definitions/DmgEffect"
        },
        {
          "$ref": "#/definitions/ArmorEffect"
        },
        {
          "$ref": "#/definitions/DotEffect"
        }
      ]
    },
    "EffectType": {
      "enum": [
        "revive",
        "heal",
        "dmg",
        "spawn-unit",
        "armor",
        "dot"
      ],
      "type": "string"
    },
    "GenericEffect": {
      "additionalProperties": false,
      "properties": {
        "type": {
          "$ref": "#/definitions/EffectType"
        }
      },
      "required": [
        "type"
      ],
      "type": "object"
    },
    "HealEffect": {
      "additionalProperties": false,
      "properties": {
        "power": {
          "type": "number"
        },
        "type": {
          "const": "heal",
          "type": "string"
        }
      },
      "required": [
        "type",
        "power"
      ],
      "type": "object"
    },
    "SeekCondition": {
      "anyOf": [
        {
          "const": "enemy-team",
          "type": "string"
        },
        {
          "const": "alive",
          "type": "string"
        },
        {
          "const": "dead",
          "type": "string"
        },
        {
          "const": "same-team",
          "type": "string"
        },
        {
          "const": "damaged",
          "type": "string"
        },
        {
          "items": [
            {
              "const": "in-distance",
              "type": "string"
            },
            {
              "additionalProperties": false,
              "properties": {
                "distance": {
                  "type": "number"
                }
              },
              "required": [
                "distance"
              ],
              "type": "object"
            }
          ],
          "maxItems": 2,
          "minItems": 2,
          "type": "array"
        }
      ]
    },
    "UnitConfig": {
      "additionalProperties": false,
      "properties": {
        "action": {
          "$ref": "#/definitions/Action"
        },
        "effects": {
          "items": {
            "$ref": "#/definitions/Effect"
          },
          "type": "array"
        },
        "id": {
          "type": "string"
        },
        "maxHp": {
          "type": "number"
        },
        "moveSpeed": {
          "type": "number"
        },
        "size": {
          "type": "number"
        },
        "spriteId": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "spriteId",
        "size",
        "maxHp",
        "action"
      ],
      "type": "object"
    }
  }
}

=== Greegko/battleground/packages/mods/src/mods/castle-wars/units.json
[
  {
    "id": "skeleton",
    "spriteId": "sprites/skeleton/skeleton",
    "moveSpeed": 2,
    "maxHp": 100,
    "action": {
      "animation": "attack",
      "seekTargetCondition": ["alive", "enemy-team"],
      "distance": 40,
      "cooldown": 120,
      "speed": 30,
      "hitEffect": [{ "type": "dmg", "dmgType": "physical", "power": 20 }]
    },
    "size": 32,
    "effects": [{ "type": "armor", "dmgType": "physical", "power": 10 }]
  },
  {
    "id": "archer",
    "spriteId": "sprites/archer/archer",
    "moveSpeed": 2,
    "maxHp": 100,
    "action": {
      "animation": "attack",
      "seekTargetCondition": ["alive", "enemy-team"],
      "projectileId": "sprites/projectiles/projectile",
      "distance": 400,
      "cooldown": 120,
      "speed": 30,
      "projectileSpeed": 5,
      "hitEffect": [{ "type": "dmg", "dmgType": "physical", "power": 20 }]
    },
    "size": 32
  },
  {
    "id": "necromancer",
    "spriteId": "sprites/inquisitor/inquisitor",
    "moveSpeed": 2,
    "maxHp": 100,
    "action": {
      "animation": "attack",
      "seekTargetCondition": ["dead", "same-team"],
      "distance": 100,
      "cooldown": 500,
      "speed": 60,
      "hitEffect": [{ "type": "revive" }]
    },
    "size": 32
  },
  {
    "id": "priest",
    "spriteId": "sprites/inquisitor/inquisitor",
    "moveSpeed": 2,
    "maxHp": 100,
    "action": {
      "animation": "attack",
      "seekTargetCondition": ["alive", "same-team", "damaged"],
      "distance": 100,
      "cooldown": 150,
      "speed": 60,
      "hitEffect": [{ "type": "heal", "power": 20 }]
    },
    "size": 32
  },
  {
    "id": "steam_dragon",
    "spriteId": "sprites/steam_dragon/Steam Dragon spritesheet",
    "moveSpeed": 2,
    "maxHp": 100,
    "action": {
      "animation": "attack",
      "seekTargetCondition": ["alive", "enemy-team"],
      "distance": 100,
      "cooldown": 150,
      "speed": 60,
      "hitEffect": [
        { "type": "dmg", "dmgType": "fire", "power": 7 },
        { "type": "dmg", "dmgType": "physical", "power": 7 }
      ]
    },
    "size": 32
  }
]
